# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

################################################################################
# Changes to this file requires approval from Labs. Please add a person from   #
# Labs as required approval to your MR if you have any changes.                #
################################################################################

# For pushing of release images to work, the following envionment variables have
# to set in the Gitlab UI.
# RELEASE_REGISTRY_USER
# RELEASE_REGISTRY_PASSWORD

variables:
  # Project variables
  RELEASE_REGISTRY: index.docker.io/magentaaps


stages:
  - lint
  - build
  - test
  - prerelease
  - release

# Lint stage
#############

.lint-default:
  stage: lint
  needs: []
  image: python:3.7
  services: []
  tags:
    - docker

Lint shell scripts:
  extends: .lint-default
  image: koalaman/shellcheck-alpine:latest
  before_script:
    - apk update
    - apk add git
  script:
    - git config core.quotepath off
    - git ls-files --exclude='*.sh' --ignored | grep -v job-runner.sh | xargs shellcheck --external-sources --shell=bash
