# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

################################################################################
# Changes to this file requires approval from Labs. Please add a person from   #
# Labs as required approval to your MR if you have any changes.                #
################################################################################

# For pushing of release images to work, the following envionment variables have
# to set in the Gitlab UI.
# RELEASE_REGISTRY_USER
# RELEASE_REGISTRY_PASSWORD

variables:
  # Project variables
  RELEASE_REGISTRY: index.docker.io/magentaaps


stages:
  - lint
  - build
  - test
  - prerelease
  - release


# Lint stage
############

.lint-python:
  stage: test
  needs: []
  image: python:3
  services: []
  before_script:
    - pip install -r integrations/requirements/lint.txt
  tags:
    - docker


Lint AD Integration:
  extends: .lint-python
  script:
    - cd integrations/ad_integration/
    - python -m black --line-length 85 tests/* utils.py ad_template_engine.py
    - apt-get update && apt-get install -y git
    - git diff
    - python -m isort --check-only tests/* utils.py


# Test stage
############

.test-python:
  stage: test
  needs: []
  image: python:3.5
  services: []
  before_script:
    - apt-get update && apt-get install -y unixodbc-dev freetds-dev unixodbc tdsodbc libkrb5-dev libmysqlclient-dev
    - find . -name 'requirements.*' | grep -v venv/ | xargs -l1 pip install -r
    - pip install ./os2mo_data_import --upgrade
  tags:
    - docker


Test AD Integration:
  extends: .test-python
  script:
    - cd integrations/ad_integration/
    - pytest tests/


Test OS2Sync Integration:
  extends: .test-python
  script:
    - python -m doctest integrations/os2sync/os2mo.py
