# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

################################################################################
# Changes to this file requires approval from Labs. Please add a person from   #
# Labs as required approval to your MR if you have any changes.                #
################################################################################

# For pushing of release images to work, the following envionment variables have
# to set in the Gitlab UI.
# RELEASE_REGISTRY_USER
# RELEASE_REGISTRY_PASSWORD

variables:
  # Project variables
  RELEASE_REGISTRY: index.docker.io/magentaaps


stages:
  - lint
  - build
  - test
  - prerelease
  - release


# Lint stage
############

.lint-python:
  stage: lint
  needs: []
  image: python:3
  services: []
  before_script:
    - pip install -r integrations/requirements/lint.txt
  tags:
    - docker


Lint files:
  extends: .lint-python
  script:
    - python -m black --diff --check .
    - python -m isort --profile black --diff --check-only .



# Test stage
############

.test-python:
  stage: test
  needs: []
  image: python:3
  services: []
  before_script:
    - apt-get update && apt-get install -y unixodbc-dev freetds-dev unixodbc tdsodbc libkrb5-dev libmariadb-dev-compat
    - find . -name 'requirements.*' | grep -v venv/ | xargs -l1 pip install -r
    - pip install -r ./integrations/requirements/common.txt
    - pip install -r ./integrations/requirements/test.txt
    - pip install ./os2mo_data_import --upgrade
  tags:
    - docker


Test LoraCache Exporter:
  extends: .test-python
  script:
    - apt update && apt install -y unixodbc-dev freetds-dev unixodbc tdsodbc libkrb5-dev libmariadb-dev cifs-utils
    - pip install -r exporters/sql_export/tests/requirements.txt
    - export PYTHONPATH=$PWD:$PYTHONPATH
    - pytest exporters/sql_export/tests/

Test AD Integration:
  extends: .test-python
  script:
    - cd integrations/ad_integration/
    - pytest tests/ --ignore tests/test_ad_sync.py

Test OS2Sync Integration:
  extends: .test-python
  script:
    - cp settings/kommune-andeby.json settings/settings.json
    - export PYTHONPATH=$PWD:$PYTHONPATH
    - python -m doctest integrations/os2sync/os2mo.py

Test CPR Mapper:
  extends: .test-python
  script:
    - python -m doctest -v integrations/cpr_mapper.py

Test OPUS Org Tree Print:
  extends: .test-python
  script:
    - pip install -r integrations/opus/org_tree_print/requirements.txt
    - python -m doctest -v integrations/opus/org_tree_print/main.py

Test OPUS Helpers:
  extends: .test-python
  script:
    - cp settings/kommune-andeby.json settings/settings.json
    - python -m doctest -v integrations/opus/opus_helpers.py
    
Test SDLoen Integration:
  extends: .test-python
  script:
    - export PYTHONPATH=$PWD:$PYTHONPATH
    - pip install -r integrations/requirements.txt
    - python integrations/SD_Lon/sd_cli.py --help
    - pytest integrations/SD_Lon/tests/

Test Reports:
  extends: .test-python
  script:
    - export PYTHONPATH=$PWD:$PYTHONPATH
    - pip install -r reports/requirements/test.txt
    - pytest reports/os2mo_tests/ --ignore reports/os2mo_tests/test_viborg_managers.py

Test Exporter Utils:
  extends: .test-python
  script:
    - export PYTHONPATH=$PWD:$PYTHONPATH
    - pip install -r exporters/utils/requirements.txt
    - pytest exporters/utils/tests/
